export const settings = {
  PUBLIC_REQUIRE_PAYMENT: process?.env?.NEXT_PUBLIC_REQUIRE_PAYMENT,
  ADMIN_COURSE: process?.env?.NEXT_PUBLIC_ADMIN_COURSE,
  JWT_SECRET: process?.env?.JWT_SECRET,
  THEME: process?.env?.NEXT_PUBLIC_THEME,
  BACKEND_URL: process?.env?.NEXT_PUBLIC_BACKEND_URL,
  AES_TOKEN: process?.env?.NEXT_PUBLIC_AES_TOKEN,
  RAZORPAY_KEY: process?.env?.NEXT_PUBLIC_RAZORPAY_KEY,
  IMAGE_PROTOCOL: process?.env?.NEXT_PUBLIC_IMAGE_PROTOCOL,
  IMAGE_HOSTNAME: process?.env?.NEXT_PUBLIC_IMAGE_HOSTNAME,
};
